class_name ConvoyNames
extends RefCounted

static var _next_index: int = 0

static var ADJECTIVES: PackedStringArray = [
	"Able", "Abundant", "Acute", "Adept", "Aged", "Agile", "Airy",
	"Alert", "Alpine", "Amber", "Ample", "Ancient", "Anvil", "Aqua",
	"Arch", "Ardent", "Argent", "Arid", "Ashen", "August", "Austere",
	"Avid", "Azure", "Bald", "Balmy", "Bare", "Barren", "Base",
	"Bashful", "Beady", "Bent", "Birch", "Bitter", "Black", "Bleak",
	"Blighted", "Blind", "Bliss", "Blond", "Blue", "Bluff", "Blunt",
	"Bold", "Bone", "Brash", "Brave", "Brazen", "Briar", "Brick",
	"Brief", "Bright", "Brine", "Brisk", "Brittle", "Broad", "Broken",
	"Bronze", "Brook", "Brown", "Brute", "Burnt", "Burly", "Calm",
	"Canny", "Cedar", "Chalk", "Char", "Chief", "Chill", "Civic",
	"Civil", "Clad", "Clay", "Clean", "Clear", "Cliff", "Close",
	"Cloud", "Coal", "Coarse", "Cobalt", "Cold", "Common", "Cool",
	"Copper", "Coral", "Core", "Corn", "Coy", "Crag", "Crane",
	"Crisp", "Cross", "Crow", "Crown", "Crude", "Cruel", "Crystal",
	"Curt", "Cyan", "Dagger", "Damp", "Dane", "Dapple", "Daring",
	"Dark", "Dawn", "Dead", "Dear", "Deep", "Dense", "Devout",
	"Dim", "Dire", "Dirty", "Distant", "Dour", "Draft", "Drawn",
	"Drear", "Drift", "Dry", "Dual", "Dull", "Dune", "Dusk",
	"Dusty", "Eager", "Early", "Earnest", "East", "Ebony", "Edge",
	"Elder", "Elm", "Ember", "Empty", "Equal", "Even", "Ever",
	"Exact", "Exile", "Extra", "Faded", "Fair", "Falcon", "Fallen",
	"False", "Fang", "Far", "Fast", "Fawn", "Fell", "Feral",
	"Fern", "Fervent", "Few", "Fierce", "Final", "Fine", "Firm",
	"First", "Five", "Fixed", "Fjord", "Flag", "Flame", "Flat",
	"Fleet", "Flint", "Float", "Foe", "Fog", "Fond", "Fool",
	"Forge", "Fork", "Fort", "Fossil", "Foul", "Four", "Fox",
	"Frank", "Free", "Fresh", "Friar", "Frost", "Frozen", "Full",
	"Gale", "Gall", "Garnet", "Gaunt", "Ghost", "Giant", "Gilt",
	"Glad", "Glass", "Glen", "Glint", "Gloam", "Gloom", "Gnarly",
	"Gold", "Good", "Grand", "Granite", "Grave", "Gray", "Great",
	"Green", "Grey", "Grim", "Grit", "Grove", "Gruff", "Guard",
	"Gulf", "Gust", "Hale", "Half", "Halt", "Hard", "Hardy",
	"Hare", "Harsh", "Haste", "Hawk", "Haze", "Heavy", "Hedge",
	"Helm", "Heron", "Hex", "Hidden", "High", "Hoar", "Hollow",
	"Honest", "Hope", "Horn", "Horse", "Hound", "Humble", "Hunter",
	"Hushed", "Ice", "Idle", "Ill", "Inch", "Indigo", "Inner",
	"Iron", "Isle", "Ivory", "Ivy", "Jade", "Jagged", "Jay",
	"Jet", "Jewel", "Jolly", "Judge", "Just", "Keen", "Kelp",
	"Khan", "Kin", "Kind", "Knave", "Knight", "Knoll", "Known",
	"Lake", "Lame", "Lance", "Large", "Lark", "Last", "Late",
	"Laurel", "Lavish", "Lean", "Left", "Lemon", "Less", "Level",
	"Light", "Lime", "Linden", "Lion", "Live", "Llano", "Lofty",
	"Lone", "Long", "Lost", "Loud", "Low", "Loyal", "Lucky",
	"Lunar", "Lush", "Mad", "Main", "Malt", "Many", "Maple",
	"Marble", "Marsh", "Mason", "Mass", "Matte", "Meager", "Mean",
	"Meek", "Mere", "Metal", "Mica", "Mild", "Mill", "Mine",
	"Minor", "Mint", "Mire", "Mist", "Modest", "Moist", "Mole",
	"Moon", "Moor", "Mortar", "Moss", "Mount", "Mouse", "Muddy",
	"Mule", "Musk", "Mute", "Myth", "Narrow", "Near", "Neat",
	"Nettle", "New", "Next", "Night", "Nine", "Noble", "Noon",
	"North", "Numb", "Oak", "Oaken", "Oar", "Oat", "Obsidian",
	"Odd", "Old", "Olive", "One", "Onyx", "Open", "Orbit",
	"Ore", "Osprey", "Other", "Otter", "Outer", "Over", "Oven",
	"Owl", "Oxide", "Pace", "Pact", "Pale", "Palm", "Parch",
	"Past", "Path", "Pawn", "Peak", "Pearl", "Peat", "Pewter",
	"Pick", "Pike", "Pine", "Pink", "Pitch", "Plain", "Plank",
	"Plumb", "Point", "Polar", "Pond", "Poor", "Port", "Post",
	"Pound", "Prime", "Prior", "Proud", "Pure", "Quail", "Quake",
	"Quick", "Quiet", "Quill", "Quirk", "Quite", "Quota", "Raft",
	"Rage", "Rain", "Rapid", "Rare", "Rash", "Raven", "Raw",
	"Razor", "Ready", "Real", "Red", "Reed", "Reef", "Regal",
	"Rich", "Ridge", "Rift", "Right", "Rigid", "Rim", "Rind",
	"Ring", "Ripe", "River", "Road", "Roan", "Rock", "Rogue",
	"Root", "Rope", "Rose", "Rough", "Round", "Royal", "Ruby",
	"Rude", "Rune", "Ruse", "Rush", "Rust", "Rustic", "Rye",
	"Sable", "Sad", "Sage", "Salt", "Same", "Sand", "Satin",
	"Savage", "Scale", "Scar", "Scout", "Sea", "Seal", "Second",
	"Seed", "Seven", "Shade", "Shale", "Shallow", "Sharp", "Sheer",
	"Shell", "Shield", "Shin", "Shire", "Short", "Shrike", "Shut",
	"Shy", "Siege", "Silk", "Silver", "Simple", "Single", "Siren",
	"Six", "Slate", "Sleek", "Sleet", "Slight", "Slim", "Slow",
	"Small", "Smart", "Smoke", "Smooth", "Snake", "Snow", "Snug",
	"Sober", "Soft", "Sole", "Solid", "Son", "Soon", "Soot",
	"Sore", "Sort", "Sound", "Sour", "South", "Spare", "Spark",
	"Sparse", "Spear", "Spire", "Split", "Spore", "Spruce", "Spur",
	"Square", "Staff", "Stage", "Stag", "Stake", "Stale", "Stall",
	"Stamp", "Stark", "Starve", "Stave", "Steady", "Steam", "Steel",
	"Steep", "Stem", "Stern", "Stiff", "Still", "Stock", "Stoic",
	"Stone", "Stork", "Storm", "Stout", "Strait", "Straw", "Stray",
	"Strict", "Strike", "Strong", "Stump", "Stun", "Subtle", "Sulk",
	"Sullen", "Summit", "Sun", "Sunk", "Sure", "Surge", "Swamp",
	"Swan", "Sweet", "Swift", "Sword", "Sworn", "Tame", "Tangle",
	"Tar", "Tarn", "Tart", "Taunt", "Taut", "Tawny", "Tempest",
	"Ten", "Tender", "Tense", "Tepid", "Tern", "Terra", "Thick",
	"Thin", "Third", "Thorn", "Three", "Thrift", "Tide", "Tight",
	"Timber", "Tin", "Tinder", "Titan", "Toll", "Tomb", "Top",
	"Torch", "Torn", "Total", "Tough", "Tower", "Trail", "Trap",
	"Tree", "Trend", "Trice", "Trim", "True", "Trust", "Tuft",
	"Tulip", "Tumble", "Turret", "Tusk", "Twin", "Twist", "Two",
	"Ultra", "Umber", "Under", "Unfit", "Upper", "Urban", "Urge",
	"Usual", "Utter", "Vague", "Vale", "Valid", "Valor", "Vane",
	"Vapor", "Vast", "Vault", "Veil", "Velvet", "Verse", "Vest",
	"Vexed", "Vile", "Vine", "Violet", "Vivid", "Void", "Vow",
	"Vulture", "Wade", "Walnut", "Wane", "Warm", "Warp", "Wary",
	"Waste", "Watch", "Water", "Wax", "Weak", "Wealth", "Wedge",
	"West", "Wet", "Wheat", "Whelp", "Whim", "White", "Whole",
	"Wide", "Wild", "Willow", "Wilt", "Wind", "Wine", "Winter",
	"Wire", "Wise", "Wolf", "Wood", "Wool", "Worn", "Worth",
	"Wound", "Wren", "Writ", "Wrong", "Wroth", "Yawn", "Year",
	"Yellow", "Yeoman", "Yield", "Yoke", "Young", "Zeal", "Zenith",
	"Zero", "Zinc", "Zone",
	"Alderborne",
	"Alderbound",
	"Alderbright",
	"Aldercast",
	"Alderclad",
	"Aldercrest",
	"Alderdappled",
	"Alderdriven",
	"Alderedged",
	"Alderfavored",
	"Alderforged",
	"Alderframed",
	"Aldergilded",
	"Alderglazed",
	"Aldergraced",
	"Alderguarded",
	"Alderhardened",
	"Alderkindled",
	"Aldermarked",
	"Alderveiled",
	"Amberborne",
	"Amberbound",
	"Amberbright",
	"Ambercast",
	"Amberclad",
	"Ambercrest",
	"Amberdappled",
	"Amberdriven",
	"Amberedged",
	"Amberfavored",
	"Amberforged",
	"Amberframed",
	"Ambergilded",
	"Amberglazed",
	"Ambergraced",
	"Amberguarded",
	"Amberhardened",
	"Amberkindled",
	"Ambermarked",
	"Amberveiled",
	"Arcborne",
	"Arcbound",
	"Arcbright",
	"Arccast",
	"Arcclad",
	"Arccrest",
	"Arcdappled",
	"Arcdriven",
	"Arcedged",
	"Arcfavored",
	"Arcforged",
	"Arcframed",
	"Arcgilded",
	"Arcglazed",
	"Arcgraced",
	"Arcguarded",
	"Archardened",
	"Arckindled",
	"Arcmarked",
	"Arcveiled",
	"Ashborne",
	"Ashbound",
	"Ashbright",
	"Ashcast",
	"Ashclad",
	"Ashcrest",
	"Ashdappled",
	"Ashdriven",
	"Ashedged",
	"Ashfavored",
	"Ashforged",
	"Ashframed",
	"Ashgilded",
	"Ashglazed",
	"Ashgraced",
	"Ashguarded",
	"Ashhardened",
	"Ashkindled",
	"Ashmarked",
	"Ashveiled",
	"Aspenborne",
	"Aspenbound",
	"Aspenbright",
	"Aspencast",
	"Aspenclad",
	"Aspencrest",
	"Aspendappled",
	"Aspendriven",
	"Aspenedged",
	"Aspenfavored",
	"Aspenforged",
	"Aspenframed",
	"Aspengilded",
	"Aspenglazed",
	"Aspengraced",
	"Aspenguarded",
	"Aspenhardened",
	"Aspenkindled",
	"Aspenmarked",
	"Aspenveiled",
	"Auburnborne",
	"Auburnbound",
	"Auburnbright",
	"Auburncast",
	"Auburnclad",
	"Auburncrest",
	"Auburndappled",
	"Auburndriven",
	"Auburnedged",
	"Auburnfavored",
	"Auburnforged",
	"Auburnframed",
	"Auburngilded",
	"Auburnglazed",
	"Auburngraced",
	"Auburnguarded",
	"Auburnhardened",
	"Auburnkindled",
	"Auburnmarked",
	"Auburnveiled",
	"Auricborne",
	"Auricbound",
	"Auricbright",
	"Auriccast",
	"Auricclad",
	"Auriccrest",
	"Auricdappled",
	"Auricdriven",
	"Auricedged",
	"Auricfavored",
	"Auricforged",
	"Auricframed",
	"Auricgilded",
	"Auricglazed",
	"Auricgraced",
	"Auricguarded",
	"Aurichardened",
	"Aurickindled",
	"Auricmarked",
	"Auricveiled",
	"Bastionborne",
	"Bastionbound",
	"Bastionbright",
	"Bastioncast",
	"Bastionclad",
	"Bastioncrest",
	"Bastiondappled",
	"Bastiondriven",
	"Bastionedged",
	"Bastionfavored",
	"Bastionforged",
	"Bastionframed",
	"Bastiongilded",
	"Bastionglazed",
	"Bastiongraced",
	"Bastionguarded",
	"Bastionhardened",
	"Bastionkindled",
	"Bastionmarked",
	"Bastionveiled",
	"Bayborne",
	"Baybound",
	"Baybright",
	"Baycast",
	"Bayclad",
	"Baycrest",
	"Baydappled",
	"Baydriven",
	"Bayedged",
	"Bayfavored",
	"Bayforged",
	"Bayframed",
	"Baygilded",
	"Bayglazed",
	"Baygraced",
	"Bayguarded",
	"Bayhardened",
	"Baykindled",
	"Baymarked",
	"Bayveiled",
	"Beaconborne",
	"Beaconbound",
	"Beaconbright",
	"Beaconcast",
	"Beaconclad",
	"Beaconcrest",
	"Beacondappled",
	"Beacondriven",
	"Beaconedged",
	"Beaconfavored",
	"Beaconforged",
	"Beaconframed",
	"Beacongilded",
	"Beaconglazed",
	"Beacongraced",
	"Beaconguarded",
	"Beaconhardened",
	"Beaconkindled",
	"Beaconmarked",
	"Beaconveiled",
	"Birchborne",
	"Birchbound",
	"Birchbright",
	"Birchcast",
	"Birchclad",
	"Birchcrest",
	"Birchdappled",
	"Birchdriven",
	"Birchedged",
	"Birchfavored",
	"Birchforged",
	"Birchframed",
	"Birchgilded",
	"Birchglazed",
	"Birchgraced",
	"Birchguarded",
	"Birchhardened",
	"Birchkindled",
	"Birchmarked",
	"Birchveiled",
	"Blazeborne",
	"Blazebound",
	"Blazebright",
	"Blazecast",
	"Blazeclad",
	"Blazecrest",
	"Blazedappled",
	"Blazedriven",
	"Blazeedged",
	"Blazefavored",
	"Blazeforged",
	"Blazeframed",
	"Blazegilded",
	"Blazeglazed",
	"Blazegraced",
	"Blazeguarded",
	"Blazehardened",
	"Blazekindled",
	"Blazemarked",
	"Blazeveiled",
	"Bloomborne",
	"Bloombound",
	"Bloombright",
	"Bloomcast",
	"Bloomclad",
	"Bloomcrest",
	"Bloomdappled",
	"Bloomdriven",
	"Bloomedged",
	"Bloomfavored",
	"Bloomforged",
	"Bloomframed",
	"Bloomgilded",
	"Bloomglazed",
	"Bloomgraced",
	"Bloomguarded",
	"Bloomhardened",
	"Bloomkindled",
	"Bloommarked",
	"Bloomveiled",
	"Brackenborne",
	"Brackenbound",
	"Brackenbright",
	"Brackencast",
	"Brackenclad",
	"Brackencrest",
	"Brackendappled",
	"Brackendriven",
	"Brackenedged",
	"Brackenfavored",
	"Brackenforged",
	"Brackenframed",
	"Brackengilded",
	"Brackenglazed",
	"Brackengraced",
	"Brackenguarded",
	"Brackenhardened",
	"Brackenkindled",
	"Brackenmarked",
	"Brackenveiled",
	"Brassborne",
	"Brassbound",
	"Brassbright",
	"Brasscast",
	"Brassclad",
	"Brasscrest",
	"Brassdappled",
	"Brassdriven",
	"Brassedged",
	"Brassfavored",
	"Brassforged",
	"Brassframed",
	"Brassgilded",
	"Brassglazed",
	"Brassgraced",
	"Brassguarded",
	"Brasshardened",
	"Brasskindled",
	"Brassmarked",
	"Brassveiled",
	"Breezeborne",
	"Breezebound",
	"Breezebright",
	"Breezecast",
	"Breezeclad",
	"Breezecrest",
	"Breezedappled",
	"Breezedriven",
	"Breezeedged",
	"Breezefavored",
	"Breezeforged",
	"Breezeframed",
	"Breezegilded",
	"Breezeglazed",
	"Breezegraced",
	"Breezeguarded",
	"Breezehardened",
	"Breezekindled",
	"Breezemarked",
	"Breezeveiled",
	"Brimborne",
	"Brimbound",
	"Brimbright",
	"Brimcast",
	"Brimclad",
	"Brimcrest",
	"Brimdappled",
	"Brimdriven",
	"Brimedged",
	"Brimfavored",
	"Brimforged",
	"Brimframed",
	"Brimgilded",
	"Brimglazed",
	"Brimgraced",
	"Brimguarded",
	"Brimhardened",
	"Brimkindled",
	"Brimmarked",
	"Brimveiled",
	"Brindleborne",
	"Brindlebound",
	"Brindlebright",
	"Brindlecast",
	"Brindleclad",
	"Brindlecrest",
	"Brindledappled",
	"Brindledriven",
	"Brindleedged",
	"Brindlefavored",
	"Brindleforged",
	"Brindleframed",
	"Brindlegilded",
	"Brindleglazed",
	"Brindlegraced",
	"Brindleguarded",
	"Brindlehardened",
	"Brindlekindled",
	"Brindlemarked",
	"Brindleveiled",
	"Brookborne",
	"Brookbound",
	"Brookbright",
	"Brookcast",
	"Brookclad",
	"Brookcrest",
	"Brookdappled",
	"Brookdriven",
	"Brookedged",
	"Brookfavored",
	"Brookforged",
	"Brookframed",
	"Brookgilded",
	"Brookglazed",
	"Brookgraced",
	"Brookguarded",
	"Brookhardened",
	"Brookkindled",
	"Brookmarked",
	"Brookveiled",
	"Cairnborne",
	"Cairnbound",
	"Cairnbright",
	"Cairncast",
	"Cairnclad",
	"Cairncrest",
	"Cairndappled",
	"Cairndriven",
	"Cairnedged",
	"Cairnfavored",
	"Cairnforged",
	"Cairnframed",
	"Cairngilded",
	"Cairnglazed",
	"Cairngraced",
	"Cairnguarded",
	"Cairnhardened",
	"Cairnkindled",
	"Cairnmarked",
	"Cairnveiled",
	"Candleborne",
	"Candlebound",
	"Candlebright",
	"Candlecast",
	"Candleclad",
	"Candlecrest",
	"Candledappled",
	"Candledriven",
	"Candleedged",
	"Candlefavored",
	"Candleforged",
	"Candleframed",
	"Candlegilded",
	"Candleglazed",
	"Candlegraced",
	"Candleguarded",
	"Candlehardened",
	"Candlekindled",
	"Candlemarked",
	"Candleveiled",
	"Cinderborne",
	"Cinderbound",
	"Cinderbright",
	"Cindercast",
	"Cinderclad",
	"Cindercrest",
	"Cinderdappled",
	"Cinderdriven",
	"Cinderedged",
	"Cinderfavored",
	"Cinderforged",
	"Cinderframed",
	"Cindergilded",
	"Cinderglazed",
	"Cindergraced",
	"Cinderguarded",
	"Cinderhardened",
	"Cinderkindled",
	"Cindermarked",
	"Cinderveiled",
	"Cobaltborne",
	"Cobaltbound",
	"Cobaltbright",
	"Cobaltcast",
	"Cobaltclad",
	"Cobaltcrest",
	"Cobaltdappled",
	"Cobaltdriven",
	"Cobaltedged",
	"Cobaltfavored",
	"Cobaltforged",
	"Cobaltframed",
	"Cobaltgilded",
	"Cobaltglazed",
	"Cobaltgraced",
	"Cobaltguarded",
	"Cobalthardened",
	"Cobaltkindled",
	"Cobaltmarked",
	"Cobaltveiled",
	"Cometborne",
	"Cometbound",
	"Cometbright",
	"Cometcast",
	"Cometclad",
	"Cometcrest",
	"Cometdappled",
	"Cometdriven",
	"Cometedged",
	"Cometfavored",
	"Cometforged",
	"Cometframed",
	"Cometgilded",
	"Cometglazed",
	"Cometgraced",
	"Cometguarded",
	"Comethardened",
	"Cometkindled",
	"Cometmarked",
	"Cometveiled",
	"Crimsonborne",
	"Crimsonbound",
	"Crimsonbright",
	"Crimsoncast",
	"Crimsonclad",
	"Crimsoncrest",
	"Crimsondappled",
	"Crimsondriven",
	"Crimsonedged",
	"Crimsonfavored",
	"Crimsonforged",
	"Crimsonframed",
	"Crimsongilded",
	"Crimsonglazed",
	"Crimsongraced",
	"Crimsonguarded",
	"Crimsonhardened",
	"Crimsonkindled",
	"Crimsonmarked",
	"Crimsonveiled",
	"Crownborne",
	"Crownbound",
	"Crownbright",
	"Crowncast",
	"Crownclad",
	"Crowncrest",
	"Crowndappled",
	"Crowndriven",
	"Crownedged",
	"Crownfavored",
	"Crownforged",
	"Crownframed",
	"Crowngilded",
	"Crownglazed",
	"Crowngraced",
	"Crownguarded",
	"Crownhardened",
	"Crownkindled",
	"Crownmarked",
	"Crownveiled",
	"Dawnborne",
	"Dawnbound",
	"Dawnbright",
	"Dawncast",
	"Dawnclad",
	"Dawncrest",
	"Dawndappled",
	"Dawndriven",
	"Dawnedged",
	"Dawnfavored",
	"Dawnforged",
	"Dawnframed",
	"Dawngilded",
	"Dawnglazed",
	"Dawngraced",
	"Dawnguarded",
	"Dawnhardened",
	"Dawnkindled",
	"Dawnmarked",
	"Dawnveiled",
	"Dewborne",
	"Dewbound",
	"Dewbright",
	"Dewcast",
	"Dewclad",
	"Dewcrest",
	"Dewdappled",
	"Dewdriven",
	"Dewedged",
	"Dewfavored",
	"Dewforged",
	"Dewframed",
	"Dewgilded",
	"Dewglazed",
	"Dewgraced",
	"Dewguarded",
	"Dewhardened",
	"Dewkindled",
	"Dewmarked",
	"Dewveiled",
	"Drakeborne",
	"Drakebound",
	"Drakebright",
	"Drakecast",
	"Drakeclad",
	"Drakecrest",
	"Drakedappled",
	"Drakedriven",
	"Drakeedged",
	"Drakefavored",
	"Drakeforged",
	"Drakeframed",
	"Drakegilded",
	"Drakeglazed",
	"Drakegraced",
	"Drakeguarded",
	"Drakehardened",
	"Drakekindled",
	"Drakemarked",
	"Drakeveiled",
	"Duneborne",
	"Dunebound",
	"Dunebright",
	"Dunecast",
	"Duneclad",
	"Dunecrest",
	"Dunedappled",
	"Dunedriven",
	"Duneedged",
	"Dunefavored",
	"Duneforged",
	"Duneframed",
	"Dunegilded",
	"Duneglazed",
	"Dunegraced",
	"Duneguarded",
	"Dunehardened",
	"Dunekindled",
	"Dunemarked",
	"Duneveiled",
	"Eagleborne",
	"Eaglebound",
	"Eaglebright",
	"Eaglecast",
	"Eagleclad",
	"Eaglecrest",
	"Eagledappled",
	"Eagledriven",
	"Eagleedged",
	"Eaglefavored",
	"Eagleforged",
	"Eagleframed",
	"Eaglegilded",
	"Eagleglazed",
	"Eaglegraced",
	"Eagleguarded",
	"Eaglehardened",
	"Eaglekindled",
	"Eaglemarked",
	"Eagleveiled",
	"Echoborne",
	"Echobound",
	"Echobright",
	"Echocast",
	"Echoclad",
	"Echocrest",
	"Echodappled",
	"Echodriven",
	"Echoedged",
	"Echofavored",
	"Echoforged",
	"Echoframed",
	"Echogilded",
	"Echoglazed",
	"Echograced",
	"Echoguarded",
	"Echohardened",
	"Echokindled",
	"Echomarked",
	"Echoveiled",
	"Elmborne",
	"Elmbound",
	"Elmbright",
	"Elmcast",
	"Elmclad",
	"Elmcrest",
	"Elmdappled",
	"Elmdriven",
	"Elmedged",
	"Elmfavored",
	"Elmforged",
	"Elmframed",
	"Elmgilded",
	"Elmglazed",
	"Elmgraced",
	"Elmguarded",
	"Elmhardened",
	"Elmkindled",
	"Elmmarked",
	"Elmveiled",
	"Emberborne",
	"Emberbound",
	"Emberbright",
	"Embercast",
	"Emberclad",
	"Embercrest",
	"Emberdappled",
	"Emberdriven",
	"Emberedged",
	"Emberfavored",
	"Emberforged",
	"Emberframed",
	"Embergilded",
	"Emberglazed",
	"Embergraced",
	"Emberguarded",
	"Emberhardened",
	"Emberkindled",
	"Embermarked",
	"Emberveiled",
	"Falconborne",
	"Falconbound",
	"Falconbright",
	"Falconcast",
	"Falconclad",
	"Falconcrest",
	"Falcondappled",
	"Falcondriven",
	"Falconedged",
	"Falconfavored",
	"Falconforged",
	"Falconframed",
	"Falcongilded",
	"Falconglazed",
	"Falcongraced",
	"Falconguarded",
	"Falconhardened",
	"Falconkindled",
	"Falconmarked",
	"Falconveiled",
	"Fallowborne",
	"Fallowbound",
	"Fallowbright",
	"Fallowcast",
	"Fallowclad",
	"Fallowcrest",
	"Fallowdappled",
	"Fallowdriven",
	"Fallowedged",
	"Fallowfavored",
	"Fallowforged",
	"Fallowframed",
	"Fallowgilded",
	"Fallowglazed",
	"Fallowgraced",
	"Fallowguarded",
	"Fallowhardened",
	"Fallowkindled",
	"Fallowmarked",
	"Fallowveiled",
	"Fawnborne",
	"Fawnbound",
	"Fawnbright",
	"Fawncast",
	"Fawnclad",
	"Fawncrest",
	"Fawndappled",
	"Fawndriven",
	"Fawnedged",
	"Fawnfavored",
	"Fawnforged",
	"Fawnframed",
	"Fawngilded",
	"Fawnglazed",
	"Fawngraced",
	"Fawnguarded",
	"Fawnhardened",
	"Fawnkindled",
	"Fawnmarked",
	"Fawnveiled",
	"Fernborne",
	"Fernbound",
	"Fernbright",
	"Ferncast",
	"Fernclad",
	"Ferncrest",
	"Ferndappled",
	"Ferndriven",
	"Fernedged",
	"Fernfavored",
	"Fernforged",
	"Fernframed",
	"Ferngilded",
	"Fernglazed",
	"Ferngraced",
	"Fernguarded",
	"Fernhardened",
	"Fernkindled",
	"Fernmarked",
	"Fernveiled",
	"Flareborne",
	"Flarebound",
	"Flarebright",
	"Flarecast",
	"Flareclad",
	"Flarecrest",
	"Flaredappled",
	"Flaredriven",
	"Flareedged",
	"Flarefavored",
	"Flareforged",
	"Flareframed",
	"Flaregilded",
	"Flareglazed",
	"Flaregraced",
	"Flareguarded",
	"Flarehardened",
	"Flarekindled",
	"Flaremarked",
	"Flareveiled",
	"Flintborne",
	"Flintbound",
	"Flintbright",
	"Flintcast",
	"Flintclad",
	"Flintcrest",
	"Flintdappled",
	"Flintdriven",
	"Flintedged",
	"Flintfavored",
	"Flintforged",
	"Flintframed",
	"Flintgilded",
	"Flintglazed",
	"Flintgraced",
	"Flintguarded",
	"Flinthardened",
	"Flintkindled",
	"Flintmarked",
	"Flintveiled",
	"Frostborne",
	"Frostbound",
	"Frostbright",
	"Frostcast",
	"Frostclad",
	"Frostcrest",
	"Frostdappled",
	"Frostdriven",
	"Frostedged",
	"Frostfavored",
	"Frostforged",
	"Frostframed",
	"Frostgilded",
	"Frostglazed",
	"Frostgraced",
	"Frostguarded",
	"Frosthardened",
	"Frostkindled",
	"Frostmarked",
	"Frostveiled",
]


static func next_name(goods_name: String) -> String:
	var adj := ADJECTIVES[_next_index % ADJECTIVES.size()]
	_next_index += 1
	return "%s %s Convoy" % [adj, goods_name.capitalize()]
