class_name StatName
enum I {
	MORALE, MV_SPD, WEAPON, ARMOUR, HP,
	STA, ORG, POS, MAG, LOC,
	STRENGTH, DEX, ACR, SPD, SIZ, INT_STAT,
	SPR, FAI, CHA, BEU, WIL, ENDURANCE,
}

const BASE_ATTRIBUTE_STATS: Array[I] = [
	I.STRENGTH, I.DEX, I.ACR, I.SPD, I.SIZ,
	I.INT_STAT, I.SPR, I.FAI, I.CHA, I.BEU, I.WIL, I.ENDURANCE,
]
